#############################################################################
# Makefile for building: LearnQtTutorial
# Generated by qmake (3.1) (Qt 5.12.1)
# Project:  LearnQtTutorial.pro
# Template: subdirs
# Command: D:\Qt\5.12.1\mingw73_64\bin\qmake.exe -o Makefile LearnQtTutorial.pro -Wall
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = D:\Qt\5.12.1\mingw73_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\Qt\5.12.1\mingw73_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\Qt\5.12.1\mingw73_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-cm-lib \
		sub-cm-tests \
		sub-cm-ui


sub-cm-lib-qmake_all:  FORCE
	@if not exist cm-lib\ mkdir cm-lib\ & if not exist cm-lib\ exit 1
	cd cm-lib\ && $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-lib\cm-lib.pro -Wall
	cd cm-lib\ && $(MAKE) -f Makefile qmake_all
sub-cm-lib: FORCE
	@if not exist cm-lib\ mkdir cm-lib\ & if not exist cm-lib\ exit 1
	cd cm-lib\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-lib\cm-lib.pro -Wall ) && $(MAKE) -f Makefile
sub-cm-lib-make_first: FORCE
	@if not exist cm-lib\ mkdir cm-lib\ & if not exist cm-lib\ exit 1
	cd cm-lib\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-lib\cm-lib.pro -Wall ) && $(MAKE) -f Makefile 
sub-cm-lib-all: FORCE
	@if not exist cm-lib\ mkdir cm-lib\ & if not exist cm-lib\ exit 1
	cd cm-lib\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-lib\cm-lib.pro -Wall ) && $(MAKE) -f Makefile all
sub-cm-lib-clean: FORCE
	@if not exist cm-lib\ mkdir cm-lib\ & if not exist cm-lib\ exit 1
	cd cm-lib\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-lib\cm-lib.pro -Wall ) && $(MAKE) -f Makefile clean
sub-cm-lib-distclean: FORCE
	@if not exist cm-lib\ mkdir cm-lib\ & if not exist cm-lib\ exit 1
	cd cm-lib\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-lib\cm-lib.pro -Wall ) && $(MAKE) -f Makefile distclean
sub-cm-lib-install_subtargets: FORCE
	@if not exist cm-lib\ mkdir cm-lib\ & if not exist cm-lib\ exit 1
	cd cm-lib\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-lib\cm-lib.pro -Wall ) && $(MAKE) -f Makefile install
sub-cm-lib-uninstall_subtargets: FORCE
	@if not exist cm-lib\ mkdir cm-lib\ & if not exist cm-lib\ exit 1
	cd cm-lib\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-lib\cm-lib.pro -Wall ) && $(MAKE) -f Makefile uninstall
sub-cm-tests-qmake_all:  FORCE
	@if not exist cm-tests\ mkdir cm-tests\ & if not exist cm-tests\ exit 1
	cd cm-tests\ && $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-tests\cm-tests.pro -Wall
	cd cm-tests\ && $(MAKE) -f Makefile qmake_all
sub-cm-tests: FORCE
	@if not exist cm-tests\ mkdir cm-tests\ & if not exist cm-tests\ exit 1
	cd cm-tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-tests\cm-tests.pro -Wall ) && $(MAKE) -f Makefile
sub-cm-tests-make_first: FORCE
	@if not exist cm-tests\ mkdir cm-tests\ & if not exist cm-tests\ exit 1
	cd cm-tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-tests\cm-tests.pro -Wall ) && $(MAKE) -f Makefile 
sub-cm-tests-all: FORCE
	@if not exist cm-tests\ mkdir cm-tests\ & if not exist cm-tests\ exit 1
	cd cm-tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-tests\cm-tests.pro -Wall ) && $(MAKE) -f Makefile all
sub-cm-tests-clean: FORCE
	@if not exist cm-tests\ mkdir cm-tests\ & if not exist cm-tests\ exit 1
	cd cm-tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-tests\cm-tests.pro -Wall ) && $(MAKE) -f Makefile clean
sub-cm-tests-distclean: FORCE
	@if not exist cm-tests\ mkdir cm-tests\ & if not exist cm-tests\ exit 1
	cd cm-tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-tests\cm-tests.pro -Wall ) && $(MAKE) -f Makefile distclean
sub-cm-tests-install_subtargets: FORCE
	@if not exist cm-tests\ mkdir cm-tests\ & if not exist cm-tests\ exit 1
	cd cm-tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-tests\cm-tests.pro -Wall ) && $(MAKE) -f Makefile install
sub-cm-tests-uninstall_subtargets: FORCE
	@if not exist cm-tests\ mkdir cm-tests\ & if not exist cm-tests\ exit 1
	cd cm-tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-tests\cm-tests.pro -Wall ) && $(MAKE) -f Makefile uninstall
sub-cm-ui-qmake_all:  FORCE
	@if not exist cm-ui\ mkdir cm-ui\ & if not exist cm-ui\ exit 1
	cd cm-ui\ && $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-ui\cm-ui.pro -Wall
	cd cm-ui\ && $(MAKE) -f Makefile qmake_all
sub-cm-ui: FORCE
	@if not exist cm-ui\ mkdir cm-ui\ & if not exist cm-ui\ exit 1
	cd cm-ui\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-ui\cm-ui.pro -Wall ) && $(MAKE) -f Makefile
sub-cm-ui-make_first: FORCE
	@if not exist cm-ui\ mkdir cm-ui\ & if not exist cm-ui\ exit 1
	cd cm-ui\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-ui\cm-ui.pro -Wall ) && $(MAKE) -f Makefile 
sub-cm-ui-all: FORCE
	@if not exist cm-ui\ mkdir cm-ui\ & if not exist cm-ui\ exit 1
	cd cm-ui\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-ui\cm-ui.pro -Wall ) && $(MAKE) -f Makefile all
sub-cm-ui-clean: FORCE
	@if not exist cm-ui\ mkdir cm-ui\ & if not exist cm-ui\ exit 1
	cd cm-ui\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-ui\cm-ui.pro -Wall ) && $(MAKE) -f Makefile clean
sub-cm-ui-distclean: FORCE
	@if not exist cm-ui\ mkdir cm-ui\ & if not exist cm-ui\ exit 1
	cd cm-ui\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-ui\cm-ui.pro -Wall ) && $(MAKE) -f Makefile distclean
sub-cm-ui-install_subtargets: FORCE
	@if not exist cm-ui\ mkdir cm-ui\ & if not exist cm-ui\ exit 1
	cd cm-ui\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-ui\cm-ui.pro -Wall ) && $(MAKE) -f Makefile install
sub-cm-ui-uninstall_subtargets: FORCE
	@if not exist cm-ui\ mkdir cm-ui\ & if not exist cm-ui\ exit 1
	cd cm-ui\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-ui\cm-ui.pro -Wall ) && $(MAKE) -f Makefile uninstall

Makefile: LearnQtTutorial.pro ../../../Qt/5.12.1/mingw73_64/mkspecs/win32-g++/qmake.conf ../../../Qt/5.12.1/mingw73_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/qdevice.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/device_config.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/common/g++-base.conf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/common/angle.conf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/common/windows-vulkan.conf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/common/g++-win32.conf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/qconfig.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dstudioruntime2.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dstudioruntime2_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_axbase.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_axserver.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_winextras.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/win32-g++/qmake.conf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/win32/default_pre.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/exclusive_builds_post.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/default_post.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/precompile_header.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/win32/windows.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/yacc.prf \
		../../../Qt/5.12.1/mingw73_64/mkspecs/features/lex.prf \
		LearnQtTutorial.pro
	$(QMAKE) -o Makefile LearnQtTutorial.pro -Wall
../../../Qt/5.12.1/mingw73_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/qdevice.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/device_config.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/common/sanitize.conf:
../../../Qt/5.12.1/mingw73_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.12.1/mingw73_64/mkspecs/common/g++-base.conf:
../../../Qt/5.12.1/mingw73_64/mkspecs/common/angle.conf:
../../../Qt/5.12.1/mingw73_64/mkspecs/common/windows-vulkan.conf:
../../../Qt/5.12.1/mingw73_64/mkspecs/common/g++-win32.conf:
../../../Qt/5.12.1/mingw73_64/mkspecs/qconfig.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dstudioruntime2.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_3dstudioruntime2_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_axbase.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_axserver.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_repparser.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_winextras.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/qt_config.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/win32-g++/qmake.conf:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/toolchain.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/default_pre.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/win32/default_pre.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/exclusive_builds_post.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/default_post.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/precompile_header.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/warn_on.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/qmake_use.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/file_copies.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/win32/windows.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/exceptions.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/yacc.prf:
../../../Qt/5.12.1/mingw73_64/mkspecs/features/lex.prf:
LearnQtTutorial.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile LearnQtTutorial.pro -Wall

qmake_all: sub-cm-lib-qmake_all sub-cm-tests-qmake_all sub-cm-ui-qmake_all FORCE

make_first: sub-cm-lib-make_first sub-cm-tests-make_first sub-cm-ui-make_first  FORCE
all: sub-cm-lib-all sub-cm-tests-all sub-cm-ui-all  FORCE
clean: sub-cm-lib-clean sub-cm-tests-clean sub-cm-ui-clean  FORCE
distclean: sub-cm-lib-distclean sub-cm-tests-distclean sub-cm-ui-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-cm-lib-install_subtargets sub-cm-tests-install_subtargets sub-cm-ui-install_subtargets FORCE
uninstall_subtargets: sub-cm-lib-uninstall_subtargets sub-cm-tests-uninstall_subtargets sub-cm-ui-uninstall_subtargets FORCE

sub-cm-lib-debug:
	@if not exist cm-lib\ mkdir cm-lib\ & if not exist cm-lib\ exit 1
	cd cm-lib\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-lib\cm-lib.pro -Wall ) && $(MAKE) -f Makefile debug
sub-cm-tests-debug:
	@if not exist cm-tests\ mkdir cm-tests\ & if not exist cm-tests\ exit 1
	cd cm-tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-tests\cm-tests.pro -Wall ) && $(MAKE) -f Makefile debug
sub-cm-ui-debug:
	@if not exist cm-ui\ mkdir cm-ui\ & if not exist cm-ui\ exit 1
	cd cm-ui\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-ui\cm-ui.pro -Wall ) && $(MAKE) -f Makefile debug
debug: sub-cm-lib-debug sub-cm-tests-debug sub-cm-ui-debug

sub-cm-lib-release:
	@if not exist cm-lib\ mkdir cm-lib\ & if not exist cm-lib\ exit 1
	cd cm-lib\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-lib\cm-lib.pro -Wall ) && $(MAKE) -f Makefile release
sub-cm-tests-release:
	@if not exist cm-tests\ mkdir cm-tests\ & if not exist cm-tests\ exit 1
	cd cm-tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-tests\cm-tests.pro -Wall ) && $(MAKE) -f Makefile release
sub-cm-ui-release:
	@if not exist cm-ui\ mkdir cm-ui\ & if not exist cm-ui\ exit 1
	cd cm-ui\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-ui\cm-ui.pro -Wall ) && $(MAKE) -f Makefile release
release: sub-cm-lib-release sub-cm-tests-release sub-cm-ui-release

sub-cm-lib-check:
	@if not exist cm-lib\ mkdir cm-lib\ & if not exist cm-lib\ exit 1
	cd cm-lib\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-lib\cm-lib.pro -Wall ) && $(MAKE) -f Makefile check
sub-cm-tests-check:
	@if not exist cm-tests\ mkdir cm-tests\ & if not exist cm-tests\ exit 1
	cd cm-tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-tests\cm-tests.pro -Wall ) && $(MAKE) -f Makefile check
sub-cm-ui-check:
	@if not exist cm-ui\ mkdir cm-ui\ & if not exist cm-ui\ exit 1
	cd cm-ui\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-ui\cm-ui.pro -Wall ) && $(MAKE) -f Makefile check
check: sub-cm-lib-check sub-cm-tests-check sub-cm-ui-check

sub-cm-lib-benchmark:
	@if not exist cm-lib\ mkdir cm-lib\ & if not exist cm-lib\ exit 1
	cd cm-lib\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-lib\cm-lib.pro -Wall ) && $(MAKE) -f Makefile benchmark
sub-cm-tests-benchmark:
	@if not exist cm-tests\ mkdir cm-tests\ & if not exist cm-tests\ exit 1
	cd cm-tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-tests\cm-tests.pro -Wall ) && $(MAKE) -f Makefile benchmark
sub-cm-ui-benchmark:
	@if not exist cm-ui\ mkdir cm-ui\ & if not exist cm-ui\ exit 1
	cd cm-ui\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Projects\Qt\LearnQtTutorial\cm-ui\cm-ui.pro -Wall ) && $(MAKE) -f Makefile benchmark
benchmark: sub-cm-lib-benchmark sub-cm-tests-benchmark sub-cm-ui-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

